### ISSUE TITLE
Add information on using this font.

### ISSUE THREAD

**Issue by damontgomery** [marnen/borg-sans-mono#14]
As an end user, I'm not sure how to install this font. I went so far as to install Font Forge and tried to merge the font feature file and could not get ligatures to show up with TTF or OTF.

**Comment by marnen** [comment]
As is standard for GitHub projects, downloadable binaries are in the [releases section](/marnen/borg-sans-mono/releases). I’ll add this information to the README.

**Comment by damontgomery** [comment]
Thanks!
